# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0F_10kPkr23jG7-xBMOLCth1R5RMlDY
"""

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

# Optionally, you can move the uploaded file to the root directory if it's not already there
# import os
# if 'service_account.json' in uploaded and not os.path.exists('service_account.json'):
#     os.rename(list(uploaded.keys())[0], 'service_account.json')

import requests
import os
import google.auth # Add this import for google.auth.default()
from google.colab import auth
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from datetime import datetime

# 설정 값
UNSPLASH_ACCESS_KEY = 'mOWBeIHlFNL2BTuiXdvfncxkDSbAu55etNavBh-kZT8'
GDRIVE_FOLDER_ID = '11SdZ97QTvqmZW7p2eQb5mEPrRPUDnluC'

# OAuth 인증 함수
def authenticate_google_drive():
    auth.authenticate_user()
    creds, project = google.auth.default() # Corrected: use google.auth.default()
    return build('drive', 'v3', credentials=creds)

def get_free_images(query, count=10):
    url = f"https://api.unsplash.com/photos/random?query={query}&count={count}&client_id={UNSPLASH_ACCESS_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        return [img['urls']['regular'] for img in response.json()]
    return []

def upload_to_drive(file_path, folder_id, service):
    file_metadata = {'name': os.path.basename(file_path), 'parents': [folder_id]}
    media = MediaFileUpload(file_path, mimetype='image/jpeg')
    service.files().create(body=file_metadata, media_body=media, fields='id').execute()

# Google Drive 서비스 객체 미리 인증
drive_service = authenticate_google_drive()

# 실행 로직
tags = ['cat', 'dog']
for tag in tags:
    image_urls = get_free_images(tag, count=10)
    for i, url in enumerate(image_urls):
        img_data = requests.get(url).content
        filename = f"{tag}_{datetime.now().strftime('%Y%m%d')}_{i}.jpg"

        with open(filename, 'wb') as f:
            f.write(img_data)

        upload_to_drive(filename, GDRIVE_FOLDER_ID, drive_service)
        os.remove(filename)