# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0F_10kPkr23jG7-xBMOLCth1R5RMlDY
"""

import os
import json
import requests
from google.oauth2 import service_account
from googleapiclient.discovery import build
from googleapiclient.http import MediaFileUpload
from datetime import datetime

# 1. GitHub Secrets에서 환경 변수 읽어오기
UNSPLASH_ACCESS_KEY = os.environ.get('UNSPLASH_ACCESS_KEY')
GDRIVE_JSON_STR = os.environ.get('GDRIVE_SERVICE_ACCOUNT_JSON')

# 2. 구글 드라이브 폴더 ID (본인의 폴더 ID 입력)
GDRIVE_FOLDER_ID = '1xojyX1BF8eGN1ahV_qfqmSr36V_TTD85'

# 3. 중요: Secrets에서 가져온 JSON 문자열을 실제 파일로 생성
# 깃허브 컴퓨터(Runner)가 실행될 때 임시로 'service_account.json' 파일을 만듭니다.
with open('service_account.json', 'w') as f:
    f.write(GDRIVE_JSON_STR)

GDRIVE_JSON_KEY = 'service_account.json'

def upload_to_drive(file_path, folder_id):
    creds = service_account.Credentials.from_service_account_file(
        GDRIVE_JSON_KEY, scopes=['https://www.googleapis.com/auth/drive'])
    service = build('drive', 'v3', credentials=creds)
    
    file_metadata = {'name': os.path.basename(file_path), 'parents': [folder_id]}
    media = MediaFileUpload(file_path, mimetype='image/jpeg')
    service.files().create(body=file_metadata, media_body=media, fields='id').execute()

def get_free_images(query, count=10):
    url = f"https://api.unsplash.com/photos/random?query={query}&count={count}&client_id={UNSPLASH_ACCESS_KEY}"
    response = requests.get(url)
    if response.status_code == 200:
        return [img['urls']['regular'] for img in response.json()]
    return []

def upload_to_drive(file_path, folder_id):
    # 위에서 만든 임시 파일을 사용하여 인증
    creds = service_account.Credentials.from_service_account_file(
        GDRIVE_JSON_KEY, scopes=['https://www.googleapis.com/auth/drive'])
    service = build('drive', 'v3', credentials=creds)

    file_metadata = {'name': os.path.basename(file_path), 'parents': [folder_id]}
    media = MediaFileUpload(file_path, mimetype='image/jpeg')
    service.files().create(body=file_metadata, media_body=media, fields='id').execute()
# 실행 로직
tags = ['cat', 'dog']
for tag in tags:
    image_urls = get_free_images(tag, count=10)
    for i, url in enumerate(image_urls):
        img_data = requests.get(url).content
        filename = f"{tag}_{datetime.now().strftime('%Y%m%d')}_{i}.jpg"

        with open(filename, 'wb') as f:
            f.write(img_data)

        upload_to_drive(filename, GDRIVE_FOLDER_ID)
        os.remove(filename)
